# This is a basic workflow to help you get started with Actions

name: publish night build
on: 
  schedule:
    - cron: '0 13 * * *'
jobs:
  build:
    runs-on: macos-latest
    strategy:
            matrix:
              api-level: [25, 29]
              target: [default, google_apis]

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
    - name: Run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        script: ./gradlew connectedCheck --stacktrace
    - name: Upload night
      uses: actions/upload-artifact@v2
      with:
        name: app-release-NIGHT.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
