# This is a basic workflow to help you get started with Actions

name: Post merge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  allchecks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run all checks
      run: ./gradlew check --stacktrace
      
    - uses: actions/upload-artifact@v2
      with:
        name: lint-report.html
        path: app/build/reports/lint-results.html
    
    - uses: actions/upload-artifact@v2
      with:
        name: test-report.html
        path: app/build/reports/tests/testDebugUnitTest/index.html
  instrumentationTests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run all checks
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck --stacktrace
  deploy:
    runs-on: ubuntu-latest
    needs: [allchecks, instrumentationTests]
    steps:
    - uses: actions/checkout@v2
    - name: Build snapshot
      run: ./gradlew assemble --stacktrace
    
    - uses: actions/upload-artifact@v2
      with:
        name: app-release-SNAPSHOT.apk
        path: app/build/outputs/apk.release/app-release-unsigned.apk
    

