# This is a basic workflow to help you get started with Actions

name: Create release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build release apk
      env:
        RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS  }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: ./gradlew assembleRelease --stacktrace

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.HITHUB_TOKEN}}
      
      with:
        tag_name: ${{ github.ref}}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.HITHUB_TOKEN}}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url}}
        asset_path: 'app/build/outputs/apk/release/app-release.apk'
        asset_name: 'app-release.apk'
        asset_content_type: application/zip 
